### ISSUE TITLE
Not Found when opening in new tab

### ISSUE THREAD

**Issue by andyrichardson** [guestlist/guestlist#4]
**Browser:** Google Chrome (51.0.2704.106 (64-bit))
**Severity:** Minimal

1. Navigate to the [Events List](http://guestlist.net/events)
2. CTRL + Click on an event
3. Current page will redirect to 404.

This issue does not persist when using _right-click -> open in new tab_. I assume this is the result of a JS click listener.

**Comment by BackEndCoder** [comment]
hotfix applied to master and pushed live. merge master into your branch
